# Generated by Django 4.2.7 on 2023-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
