# Generated by Django 5.0 on 2023-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebsiteDRF', '0003_blog_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='static/default.jpg', upload_to='static/'),
        ),
    ]
